### ISSUE TITLE
raise RuntimeError(f"Mismatch in number of params: ours is {len(params)}, "

### ISSUE THREAD

**Issue by xiangkanghuang** [LSimon95/megatts2#18]
When I use multiple GPUs to train the model, an error occurs in the vq module.
raise RuntimeError(f"Mismatch in number of params: ours is {len(params)}, "

**Comment by LSimon95** [comment]
You can check the branch sr24k and fix it.

**Comment by xiangkanghuang** [comment]
Thank you, the evaluation module was modified according to the sr24k branch, the problem has been fixed
