### ISSUE TITLE
关于多机训练

### ISSUE THREAD

**Issue by shanhaidexiamo** [LSimon95/megatts2#8]
您好。关于vqgan等模型的训练，我运行了python cli.py fit -c configs/config_gan.yaml ，并且把cli.py里改成了MegaGANTrainer，单机可运行。此外，我注意到您的config里有  strategy: ddp等字样，是用于配置lightning多机训练的参数。但是开启后会报错：
![image](https://github.com/LSimon95/megatts2/assets/48786488/d5d5db70-e145-4d5d-868e-905f00e6d0b0)
意思是每个gpu的模型参数存在不一致，请问该问题您是否遇到过？

**Comment by LSimon95** [comment]
VQ does not support DDP, you can replace it with your vector qualification or wait for a new commit.

**Comment by LSimon95** [comment]
Fixed on branch sr24k.
